  仿真模型   sub_083    --》smc_simulation_model

rules:
  rule:
    smc_simulation_model:
      "0":
        length: 3-4
        range:
          - "CZ2F"
          - "CZ7"
          - "CZ5B"
          - "HT01"
          - "WT01"
          - "MT01"
          - "SZ12"
          - "TZ02"
          - "SZ13"
          - "TZ03"
          - "KJZ"
      "1":
        length: 1-30
        range:
          - "LaunchWindows"
          - "LaunchPara"
          - "TraDesign"
          - "ControlTraDesign"
          - "GNC"
          - "Dynamics"
          - "DataManage"
          - "TimeManage"
          - "3DV"
          - "2DV"
      "2":
        length: 4
        range:
          - "text"
      "3":
        length: 4
      "4":
        length: 1-30
      "5":
        length: 14
        mode: 0
      "6":
        length: 1-3
        range:
          - "exe"
          - "dll"
          - "m"
          - "bat"


    其他存档数据和表单  sub_085      --》smc_other_archive_datafile

rules:
  rule:
    smc_other_archive_datafile:
      "0":
        length: 2
        range:
          - "01"
      "1":
        length: 4
        range:
          - "1491"
          - "1591"
          - "1691"
          - "1791"
          - "1C90"
          - "1D90"
          - "1E90"
          - "1293"
          - "1393"
          - "1493"
          - "0000"
      "2":
        length: 8
        range:
          - "10110100"
          - "10110200"
          - "3A150300"
          - "3B750100"
          - "3B750200"
      "3":
        length: 8
        range:
          - "00220101"
          - "00020201"
          - "002A0202"
      "4":
        length: 1-30
      "5":
        length: 9
        mode: 0
      "6":
        length: 4
        mode: 0
      "7":
        length: 3
        range:
          - "dat"
          - "doc"
          - "txt"


            有效载荷
存档原始数据命名
rules:
  rule:
    pmc_arch_raw_data:
      "0":
        length: 2
        range:
          - "CT"
          - "BA"
          - "ELSE"
      "1":
        length: 5
        range:
          - "TL1A1"
          - "TL1A2"
          - "TL1B1"
          - "TL1B2"
          - "00000"
      "2":
        length: 4
        range:
          - "TGTH"
          - "TGTX"
          - "TGWT"
          - "TGMT"
          - "TGXT"
          - "SZ12"
          - "TZ01"
          - "ELSE"
      "3":
        length: 3-5
        range:
          - "AUXI"
          - "SGYC"
          - "GCYC"
          - "VCID1"
          - "VCID2"
      "4":
        length: 14
        mode: 0
      "5":
        length: 14
        mode: 0
      "6":
        length: 14
        mode: 0
      "7":
        length: 1
        range:
          - "M"
          - "B"
      "8":
        length: 5
        mode: 0
      "9":
        range:
          - "raw"


rules:
  rule:
    poac:
      archive:
        sa:
          "0":
            length: 4
            range:
              - "MSSS"
              - "TGTH"
              - "TGMT"
              - "ELSE"
            mode: A|0
          "1":
            length: 4
            range:
              - "HSRR"
              - "MSAR"
              - "CMER"
              - "HMSR"
              - "SEMP"
              - "MSAR"
              - "AIH1"
              - "AIH2"
              - "LDDT"
              - "FLCC"
              - "AMC1"
              - "AMC2"
            mode: A|0
          "2":
            length: 4
            range:
              - "CSDO"
              - "MAMO"
              - "SCAI"
              - "MSAE"
              - "PFSD"
              - "ADM1"
              - "EP01"
              - "EP03"
              - "EP05"
              - "EP07"
              - "EP09"
              - "AIRM"
              - "TCPL"
              - "TCSE"
            mode: A|0
          "3":
            length: 3-4
            range:
              - "SCI"
              - "ENG"
              - "TTC"
              - "AUX"
              - "OTHR"
            mode: A|0
          "4":
            length: 14
            mode: 0
          "5":
            length: 14
            mode: 0
          "6":
            length: 5
            mode: 0
          "7":
            length: 5
            mode: 0
          "8":
            length: 2
            range:
              - "L0"
              - "L1"
              - "OA"
              - "OB"
            mode: A|0
          "9":
            length: 2
            mode: 0
          "10":
            range:
              - "cvs"
              - "jpg"
            mode: a|0